### ISSUE TITLE
Error: exitcode=356

### ISSUE THREAD

**Issue by bemarek** [OttoAllmendinger/gnome-shell-screenshot#169] opened 2021-11-29 08:45 UTC
After moving to F35 (Gnome 41) not possible to use gnome-shell-screenshot.

I encounter this error regardless the method of taking screenshot used:

```
[hostname] gnome-shell[3254]: JS ERROR: Error: cmd: gjs /home/[logname]/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/auxhelper.js --filename /tmp/gnome-shell-screenshot-SYM0D1.png --desktop exitCode=256
                                            spawnAsync/</<@/home/[logname]/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:469:30
```

**Comment by OttoAllmendinger** [comment] 2021-11-29 08:51
duplicate of #158

**Closed by OttoAllmendinger** 2021-11-29 08:51 UTC
