### ISSUE TITLE
TypeError this.gtkImage.pixbuf is null

### ISSUE THREAD

**Issue by domhaas** [OttoAllmendinger/gnome-shell-screenshot#166] opened 2021-11-20 18:56 UTC
Since I've switched from Ubuntu to Manjaro (Gnome 41.1) I'm getting these two errors when creating a screenshot:

`error: exitCode=256`
`TypeError this.gtkImage.pixbuf is null`

Am I missing something? Couldn't find anything with these errors. Thank you in advance.

**Comment by domhaas** [comment] 2021-11-22 10:43
Possible duplicate of #165

**Comment by MisterPresident** [comment] 2021-11-28 09:30
I have the same issue, any solutions yet?

**Comment by OttoAllmendinger** [comment] 2021-11-28 12:42
This particular issue should be fixed on the `master` branch

However there are other issues with Gnome41 that need fixing.

**Comment by OttoAllmendinger** [comment] 2021-11-28 13:23
duplicate of #158

**Closed by OttoAllmendinger** 2021-11-28 13:23 UTC
