### ISSUE TITLE
Default Filename Parameters seem undefined. What to do?

### ISSUE THREAD

**Issue by AxelMKlein** [OttoAllmendinger/gnome-shell-screenshot#26] opened 2017-04-21 09:44 UTC
Hi *,

As you can see from the screenshot, the default filename parameters seem to be undefined.
What can I do?

Thank you in advance for an advice.
Best regards
Axel

![image](https://cloud.githubusercontent.com/assets/27835742/25272290/92dd8b86-2687-11e7-8396-4ee3a815a0af.png)

**Comment by OttoAllmendinger** [comment] 2017-04-21 11:13
I can't seem to reproduce this locally. Are you using the most recent version from extensions.gnome.org? 

Is there any output from the gnome shell?

Is there any error output when you start the preferences with this command: 
```
gnome-shell-extension-prefs gnome-shell-screenshot@ttll.de
```

**Comment by AxelMKlein** [comment] 2017-04-21 11:39
Hello Otto,

Yes, I use the most recent version from extensions.gnome.org. I just 
upgraded, but the result is the same.

No, I don't see an output from the gnome shell. Where would it be?

This is the output from your suggested command:

~$ gnome-shell-extension-prefs gnome-shell-screenshot@ttll.de
Gjs-Message: JS WARNING: 
[resource:///org/gnome/shell/extensionPrefs/main.js 157]: reference to 
undefined property Gio.SettingsBindFlags.BIND_DEFAULT
Gjs-Message: JS LOG: Extension 
workspace-indicator@gnome-shell-extensions.gcampax.github.com already 
installed in 
/home/axel/.local/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com. 
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com 
will not be loaded
Gjs-Message: JS LOG: binding: shortcut-select-area description: Bereich 
auswählen
Gjs-Message: JS LOG: binding: shortcut-select-window description: 
Fenster auswählen
Gjs-Message: JS LOG: binding: shortcut-select-desktop description: 
Gesamten Bildschirm auswählen
Gtk-Message: GtkDialog mapped without a transient parent. This is 
discouraged.

Thank you for your quick reply and your effort.
Best regards
Axel Klein



Am 21.04.2017 um 13:13 schrieb Otto Allmendinger:

**Comment by OttoAllmendinger** [comment] 2017-04-21 11:43
The gnome shell output can (likely) be viewed with `journalctl /usr/bin/gnome-shell -f`. 

However I realized that you don't actually need it so I removed it from my reply ;)

Can you also give me your OS and gnome-shell version? (`gnome-shell --version`)

**Comment by AxelMKlein** [comment] 2017-04-21 11:59
- OS: Ubuntu 17.04 64 Bit
This was a pure Unity (7) installation. After the Canonical announcement 
about abandoning it I installed the Gnome-Shell.

- ~$ gnome-shell --version
GNOME Shell 3.24.0

Best regards
Axel

Am 21.04.2017 um 13:43 schrieb Otto Allmendinger:

**Comment by OttoAllmendinger** [comment] 2017-04-21 12:05
I see, gnome on Ubuntu is now more bleeding edge than on Arch. I haven't had the chance to test the extension on 3.24, since I'm still on 3.22. It is a bit odd that you could even install my extension from extensions.gnome.org, since I haven't added the version string for your Gnome version. 

I'll try and update my gnome version and try to reproduce then.

**Comment by RaphaelRochet** [comment] 2017-04-24 13:23
3.24 has been promoted in Arch stable, and this behavior is visible for me too

**Comment by OttoAllmendinger** [comment] 2017-04-24 13:26
It should be fixed in the master branch, e.g.o version is pending review

**Comment by RaphaelRochet** [comment] 2017-04-24 13:27
You rocks. Thanks :)

**Comment by AxelMKlein** [comment] 2017-04-24 13:42
Thanks a lot for fixing it!

Since I'm new to gnome-shell: How can I get the fix?
Can I expect it to show up as an update-button in 'extensions.gnome.org' soon?

Best regards
Axel

**Comment by OttoAllmendinger** [comment] 2017-04-24 13:48
@AxelMKlein yes, it should be there in a few days. 

If you're eager, you can install it from source (see Readme instructions). However, then you have to be careful not to overwrite from extensions.gnome.org again ;)

**Comment by AxelMKlein** [comment] 2017-04-24 14:45
Thank you! 

So I will wait until it shows up as official update. 

Best regards
Axel

Am 24. April 2017 15:48:45 MESZ schrieb Otto Allmendinger <notifications@github.com>:

**Comment by KSXGitHub** [comment] 2017-04-25 04:37
Here from Antergos, I have this problem right after upgrade to gnome 3.24.1

**Comment by OttoAllmendinger** [comment] 2017-04-27 07:20
New version available on extensions.gnome.org, please test

**Comment by KSXGitHub** [comment] 2017-04-27 08:29
@OttoAllmendinger I worked correctly, thanks

**Closed** 2017-05-08 10:43 UTC

**Comment by AxelMKlein** [comment] 2017-05-08 10:54
Oh ja, ich vergaß die Rückmeldung. 

Funktioniert jetzt einwandfrei! 

Danke! 

Axel

Am 8. Mai 2017 12:43:46 MESZ schrieb Otto Allmendinger <notifications@github.com>:
