### ISSUE TITLE
Slider does not have signal "value-changed"

### ISSUE THREAD

**Issue by mokilcde** [OttoAllmendinger/gnome-shell-screenshot#92] opened 2019-08-15 13:05 UTC
Hi!

I got the following message after updating to Gnome Shell version 3.33.90:
gnome-shell[2532]: Extension "gnome-shell-screenshot@ttll.de" had error: Error: No signal 'value-changed' on object 'Gjs_Slider'

Here is the complete output
gnome-shell[2532]: Usage of object.actor is deprecated for PanelMenuButton#012get@resource:///org/gnome/shell/ui/environment.js:235:29#012Indicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/indicator.js:253:5#012_createIndicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:207:25#012_updateIndicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:224:7#012Extension@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:180:5#012enable@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:330:16#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:130:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:477:13#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:456:9#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:486:13#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:517:13#012init@resource:///org/gnome/shell/ui/extensionSystem.js:31:9#012_initializeUI@resource:///org/gnome/shell/ui/main.js:239:5#012start@resource:///org/gnome/shell/ui/main.js:139:5#012@
:1:31
gnome-shell[2532]: Usage of object.actor is deprecated for PanelMenuButton#012get@resource:///org/gnome/shell/ui/environment.js:235:29#012Indicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/indicator.js:254:5#012_createIndicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:207:25#012_updateIndicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:224:7#012Extension@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:180:5#012enable@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:330:16#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:130:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:477:13#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:456:9#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:486:13#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:517:13#012init@resource:///org/gnome/shell/ui/extensionSystem.js:31:9#012_initializeUI@resource:///org/gnome/shell/ui/main.js:239:5#012start@resource:///org/gnome/shell/ui/main.js:139:5#012@:1:31
gnome-shell[2532]: Extension "gnome-shell-screenshot@ttll.de" had error: Error: No signal 'value-changed' on object 'Gjs_Slider'

CU
  Michael

**Comment by OttoAllmendinger** [comment] 2019-09-07 08:42
duplicate of #93

**Closed by OttoAllmendinger** 2019-09-07 08:42 UTC
