### ISSUE TITLE
Add Pic Edit Function

### ISSUE THREAD

**Issue by 0xff91** [OttoAllmendinger/gnome-shell-screenshot#85] opened 2019-02-03 03:03 UTC
hello
Thank you for this extension, i really love it.

I would like to suggest a function, after finished screenshot, we can edit this pic simplly. just like this
![y a 5x e r 7ppyz cvqsj3](https://user-images.githubusercontent.com/16955088/52172088-56261680-27a3-11e9-818e-e437a4fbfb75.png)

**Comment by OttoAllmendinger** [comment] 2019-09-28 16:14
duplicate of https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/35

**Closed by OttoAllmendinger** 2019-09-28 16:14 UTC
