### ISSUE TITLE
Incompatible with Gnome 41

### ISSUE THREAD

**Issue by zrno** [OttoAllmendinger/gnome-shell-screenshot#165] opened 2021-11-17 05:15 UTC
Stopped working since I updated to Gnome 41.

**Comment by Modedrain** [comment] 2021-11-17 14:06
Can confirm, same issue. Selection cursor/window mark shows up when pressing hotkey but no image gets taken since upgrading to gnome 41

**Comment by diwakargoel** [comment] 2021-11-18 00:32
duplicate of https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/158

**Comment by hadeschen** [comment] 2021-11-25 12:47
臣，复议！

**Comment by OttoAllmendinger** [comment] 2021-11-28 13:21
Please try #168

**Comment by OttoAllmendinger** [comment] 2021-11-28 13:23
duplicate of #158

**Closed by OttoAllmendinger** 2021-11-28 13:23 UTC
