### ISSUE TITLE
Upload to actual imgur account?

### ISSUE THREAD

**Issue by MostHated** [OttoAllmendinger/gnome-shell-screenshot#89] opened 2019-05-15 20:13 UTC
Hey there,
    This seems like a great tool, nice to actually have an interface, but I was wondering if you had any plans on making it so you can log into and upload directly to your own imgur account? I up lots of things to a private album so I don't have to worry as much if I accidentally upload something displaying personal information.

Thanks,
-MH

**Comment by OttoAllmendinger** [comment] 2019-06-11 12:36
someday maybe ;)

duplicate of #89

**Closed by OttoAllmendinger** 2019-06-11 12:36 UTC
