### ISSUE TITLE
Overlay captured with screenshot

### ISSUE THREAD

**Issue by flolivaud** [OttoAllmendinger/gnome-shell-screenshot#65] opened 2018-03-23 08:30 UTC
Overlay is captured with screenshots (all of them):
- GNOME Shell 3.26.2
- Ubuntu 17.10
![](https://i.imgur.com/69FHKUS.png)

**Comment by OttoAllmendinger** [comment] 2018-03-23 22:59
duplicate of #28 

most recent version of master branch has a delay option, please try different delay values

if you don't want to install from git repo you can wait until it gets approved on https://extensions.gnome.org/extension/1112/screenshot-tool/

**Closed by OttoAllmendinger** 2018-03-23 22:59 UTC
