### ISSUE TITLE
feature request >> basic editing tool ?

### ISSUE THREAD

**Issue by dgoosens** [OttoAllmendinger/gnome-shell-screenshot#99] opened 2019-09-26 13:14 UTC
hi,

Wondering if there are plans or if it would be feasible to implement a basic editing tool ?

- resize
- drop down shadows
- show something with an arrow
- highlight text
- put a rectangle around something

Any plans for something like that ?
dGO

**Comment by OttoAllmendinger** [comment] 2019-09-28 16:12
duplicate of https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/35

**Closed by OttoAllmendinger** 2019-09-28 16:12 UTC
