### ISSUE TITLE
Add a "clear" feature/menu item

### ISSUE THREAD

**Issue by ddnexus** [OttoAllmendinger/gnome-shell-screenshot#40] opened 2017-05-31 09:41 UTC
Remove an old screenshot (still shown in the dropdown) that the user may not want anymore. It could be done automatically after a few seconds/minutes (option in settings) or even just manually with a "Clear" menu item. Thanks!

**Comment by OttoAllmendinger** [comment] 2017-05-31 10:03
Duplicate of #37 

The extension is still pending review on extensions.gnome.org though, sorry. If you want you can also install from the git repo.

**Closed by OttoAllmendinger** 2017-05-31 10:03 UTC

**Comment by ddnexus** [comment] 2017-05-31 10:11
Oh... great!!! Thanks!
