### ISSUE TITLE
[Feature Request] Option to repeat last screenshot

### ISSUE THREAD

**Issue by packoman** [OttoAllmendinger/gnome-shell-screenshot#103] opened 2019-10-04 08:33 UTC
Hi,

first of all thanks so much for your work on this great plugin!

This is the one thing I miss from it after switching from Shutter to this beautiful Gnome-Extension:

I often find myself repeating a screenshot of a given area of the screen. It would be great to have a button in the drop-down menu (e.g. below "Select Area", "Select Desktop", ...) to just repeat the last screenshot and which would capture the exact same area again and store it as a new screenshot.

A common use-case for me is this:
I often find myself capturing multiple screenshots of a window/area of a window, that shows a data-plot or image-plots from e.g. a program that I am working on. I do this to quickly compare results/versions side-by-side (for example).
Since usually the windows will open with same size and position, I could (in Shutter) just repeat the last screenshot, which will give me images from the exact same region, which thus have exactly the same crop and size and makes direct side-by-side comparison easy.
This is much more tedious/almost impossible, when having to precisely do the same selection by mouse.

I would therefore love to see such a feature. :)

Best,
Michael

**Comment by OttoAllmendinger** [comment] 2019-10-05 22:55
great idea, however duplicate of #75

**Closed by OttoAllmendinger** 2019-10-05 22:55 UTC
