### ISSUE TITLE
Add a time to take a screenshot

### ISSUE THREAD

**Issue by xkill** [OttoAllmendinger/gnome-shell-screenshot#63] opened 2018-02-21 13:25 UTC
I suggest to add a timer to take the screenshots, so if you have to take a screenshot after performing any action with the keyboard or mouse, you will have enough time to do it before getting the screenshot.

**Comment by OttoAllmendinger** [comment] 2018-02-21 13:49
duplicate of #2 

coming soon ;)

**Closed by OttoAllmendinger** 2018-02-21 13:49 UTC

**Comment by brunofin** [comment] 2018-03-01 16:55
It's not like I have a lot of spare time, but I am interested in learning, do you need some help for this issue maybe?
