### ISSUE TITLE
Images are captured with blue blur.

### ISSUE THREAD

**Issue by xkill** [OttoAllmendinger/gnome-shell-screenshot#62] opened 2018-02-21 13:23 UTC
Hi,

When you capture an area, the image is captured using the extension includes the blue blur used to "mark" the selected area.

See examples:
https://imgur.com/a/4sKsQ

Image captured using the extension:
![Image captured using the extension](https://i.imgur.com/GTUXHlW.png)

Image captured using Shift+Prnt Scr keys.
![Image captured using Shift+Prnt Scr keys.](https://i.imgur.com/d0krhiz.png)

**Comment by OttoAllmendinger** [comment] 2018-02-21 13:50
duplicate of #28 - please try the patch mentioned here and tell me the delay value that works for https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/28#issuecomment-356568258

**Closed by OttoAllmendinger** 2018-02-21 13:50 UTC
